# Generated by Django 3.0.6 on 2020-05-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
