# Generated by Django 3.0.6 on 2020-05-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reportexcomuna',
        ),
    ]
