# Generated by Django 3.0.6 on 2020-05-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0002_delete_reportexcomuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='RRecovered',
            field=models.FloatField(default=None),
        ),
    ]
