# Generated by Django 3.0.6 on 2020-05-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0002_auto_20200516_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
