# Generated by Django 3.0.6 on 2020-05-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0003_reportes_rrecovered'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDate',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('RDate', models.DateField(default=None)),
            ],
        ),
    ]
