# Generated by Django 3.0.6 on 2020-05-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0004_auto_20200516_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='hora',
            field=models.DateTimeField(auto_now_add=True, default='America'),
            preserve_default=False,
        ),
    ]
