# Generated by Django 3.0.6 on 2020-05-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0004_ddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ddate',
            old_name='RDate',
            new_name='RDDate',
        ),
    ]
