# Generated by Django 3.0.6 on 2020-05-25 01:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0005_auto_20200524_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
