# Generated by Django 3.0.6 on 2020-05-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0006_auto_20200524_2145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DDate',
            new_name='RRDate',
        ),
    ]
